server:
  port: 8086
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  application:
    name: snack-overflow
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?${DB_PARAM}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: YcHikariPool
      maximum-pool-size: 20
      connection-init-sql: "SET NAMES 'utf8mb4'"
      max-lifetime: 30000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: "Asia/Hong_Kong"
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: schema_version
    validate-on-migrate: true

# Spring Security and JWT
app:
  jwt:
    secret: XjPbdHPiZDO71cj1QAjyaBTIQqZL5U97Gg+GEbUW4zM=
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
  version: 1.0.0

# Line Bot Configuration (if needed)
line.bot:
  push:
    url: 'https://api.line.me/v2/bot/message/push'
  channel-token: '/KDvSta1XKaqMk32FX+tAjsgGSXK+d0hKDzuvpdbhlEgIQJ+If3PKc5Bu2U0bsOLUyEHbvjDI8s5ggCj1TU7qRVu94CuUQH16iSgCg6mN6/QDhUFqXudHLnh/lksr41e28gfkVdmRthOazTONeMk9gdB04t89/1O/w1cDnyilFU='
  channel-secret: 'e7445853b00d9657adeb4a5d572eb866'
  handler.path: /callback

# Spring Doc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
  show-actuator: true

# Spring Boot Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,flyway,env,loggers
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
