name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Test with Maven
      run: mvn test
      
    - name: Generate Javadoc
      run: mvn javadoc:javadoc
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-jar
        path: target/*.jar

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create project version badge
      run: |
        VERSION=$(grep -m 1 "<version>.*</version>" pom.xml | sed -e 's/.*<version>\(.*\)<\/version>.*/\1/')
        echo "Project version: $VERSION"
        mkdir -p badge
        echo "<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='96' height='20'><linearGradient id='b' x2='0' y2='100%'><stop offset='0' stop-color='#bbb' stop-opacity='.1'/><stop offset='1' stop-opacity='.1'/></linearGradient><clipPath id='a'><rect width='96' height='20' rx='3' fill='#fff'/></clipPath><g clip-path='url(#a)'><path fill='#555' d='M0 0h61v20H0z'/><path fill='#007ec6' d='M61 0h35v20H61z'/><path fill='url(#b)' d='M0 0h96v20H0z'/></g><g fill='#fff' text-anchor='middle' font-family='DejaVu Sans,Verdana,Geneva,sans-serif' font-size='11'><text x='30.5' y='15' fill='#010101' fill-opacity='.3'>version</text><text x='30.5' y='14'>version</text><text x='77.5' y='15' fill='#010101' fill-opacity='.3'>$VERSION</text><text x='77.5' y='14'>$VERSION</text></g></svg>" > badge/version.svg
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: badge
        branch: gh-pages
